# Generated by Django 6.0.1 on 2026-01-31 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0002_task_assignee_task_description_task_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='comments_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
