# Generated by Django 6.0.1 on 2026-02-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0005_taskcommentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcommentmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
